### ISSUE TITLE
Support in-place transpose `x` in `CKTSO_L_MV` 

### ISSUE THREAD

**Issue by mzy2240** [chenxm1986/cktso#10]
I am not sure whether it is feasible, but I am wondering if we could add an additional argument to `CKTSO_L_MV` like `transpose` so that if x is a square matrix, then we could get a transposed x directly. The benefit of doing is that sometimes the user may need to run `transpose(x)` immediately after solving `Ax = B (2D)`, having such an in-place transpose will greatly reduce the memory allocation and time cost if x is very large.
![image](https://user-images.githubusercontent.com/18620336/223440147-bc3c2ca7-020a-46ee-81bd-2eccdf0ca7d2.png)

**Comment by chenxm1986** [comment]
I don't think this is a practical need. I've never seen a sparse solver which has a similar option. In addition, this is just a special case of SolveMV when nrhs=n. Adding such an option is very strange.

**Comment by mzy2240** [comment]
It is very practical, but I agree what you said, it is indeed a special case of SolveMW when nrhs = n. Nowadays the memory bound is gradually becoming the most critical issue in the HPC area, solving linear systems can be fast, while to formulate the right structure (like transpose) could take non-neglectable amount of time.

**Comment by chenxm1986** [comment]
For practical need I mean whether transposing the solution right after solving it is needed in practical applications. The memory bandwidth problem is just a general understanding and cannot judge whether a specific function is neded or not, which is only determined by actual needs. In LAPACK, I don't see the function of transposing the solution, and it only supports transposing A. 
Also note that cktso is targeted at circuit simulation, but it is not a general sparse- or dense-matrix library, so handling irrelevant dense operations or general-purpose operations is not of its purpose.

**Comment by mzy2240** [comment]
I agree what you said, but I still think it is a reasonable feature. Array, or matrix, in some language, is row-based, while in others might be column-based. The support can be meaningful in this case as well. And I am fully aware this solver is developed for circuit simulation, and I am currently using it on power system simulation which I think it is fair to say it belongs to the great scope of circuit analysis. But anyway, close for now.
