### ISSUE TITLE
Support custom or natural ordering

### ISSUE THREAD

**Issue by mzy2240** [chenxm1986/cktso#4]
Relevant to https://github.com/chenxm1986/cktso/issues/2, since we are dealing with b which the number of columns may greatly exceeds the number of rows, factorization time does not matter anymore, but rather the quality of factorization, or more specifically the number of fills really matters and could result in an even 10% difference on the total computation time. If possible, we would like to use our own optimized ordering and skip the built-in AMD or any MD algorithm.

**Comment by chenxm1986** [comment]
Already supported. See input parm[2]. Actually I have heavily optimized the ordering. For circuit matrices, the ordering of CKTSO reduces about 20-40% arithmetic operations compared with AMD.

**Comment by mzy2240** [comment]
That’s impressive! I will definitely try to incorporate this once 2D b vector is supported
