### ISSUE TITLE
Support single precision

### ISSUE THREAD

**Issue by mzy2240** [chenxm1986/cktso#6]
KLU does not support single precision, and it seems cktso does not as well. How hard to add support for single precision? And just wonder what's the reason behind that most sparse solvers do not support single precision.

**Comment by chenxm1986** [comment]
float has much lower precision and smaller value range so it can easily lead to large round-off errors and numerical overflow. float has almost no practical use in sparse solvers.

**Comment by mzy2240** [comment]
For a 3-decimal calculation, does it have to be double precision?

**Comment by chenxm1986** [comment]
No relation with how simple input data are. For a simple example, you can print 1.1 to see what it is. For float, it is 1.1000000238418579.... For double, it is 1.1000000000000001...

**Comment by mzy2240** [comment]
To me, the error is absolutely acceptable …

**Comment by chenxm1986** [comment]
This is just the input error. Errors accumulate during LU factorization. Using floats can easily lead to larger errors in the output, or even INF or NAN output. Typically for circuit simulation, we need the accuracy at least 1e-12, or the simulated circuit response may be incorrect. If you application can tolerate large errors, and the matrix is very well-conditioned (condition number is very small), using floats may generate correct LU factorization results. But this is just a special case.
