### ISSUE TITLE
Support inplace for CKTSO_L_SolveMV

### ISSUE THREAD

**Issue by mzy2240** [chenxm1986/cktso#8]
Can we have a inplace version of CKTSO_L_SolveMV? The goal is to reduce the memory allocation and usage (thus better performance). Right now we need to allocate x first in order to execute `CKTSO_L_SolveMV(id, nb, b, x, transpose)`, can we optimize the logic if the memory of b could be reused?

**Comment by chenxm1986** [comment]
use a single array for both x and b (x and b addresses can be identical)
